version: '2'
services:
    todolist-app:
        image: todolist
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://todolist-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=TodoList
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://todolist-elasticsearch:9200
        ports:
            - 8080:8080
    todolist-mongodb:
        extends:
            file: mongodb.yml
            service: todolist-mongodb
    todolist-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: todolist-elasticsearch
